import { TestConfig } from '../../models/test.interfaces';

export const STAIC_CONFIG: TestConfig = {
  shortName: 'STAIC',
  name: 'STAIC - Inventario de Ansiedad Estado-Rasgo para Niños',
  description: 'Evalúa ansiedad estado y ansiedad rasgo en niños y adolescentes',
  totalQuestions: 40,
  optionsPerQuestion: 3,
  questionType: 'NUMERIC',
  scoringType: 'LOCAL',
  sections: [
    {
      title: 'Primera Parte: Ansiedad - Estado',
      instructions: 'Lee cada frase y señala la puntuación de 1 a 3 que indique mejor cómo te sientes ahora mismo, en este momento. No hay respuestas buenas ni malas.',
      legend: ['1 = Nada', '2 = Algo', '3 = Mucho'],
      questions: [
        { index: 1, text: '1. Me siento calmado', options: 3 },
        { index: 2, text: '2. Me encuentro inquieto', options: 3 },
        { index: 3, text: '3. Me siento nervioso', options: 3 },
        { index: 4, text: '4. Me encuentro descansado', options: 3 },
        { index: 5, text: '5. Tengo miedo', options: 3 },
        { index: 6, text: '6. Estoy relajado', options: 3 },
        { index: 7, text: '7. Estoy preocupado', options: 3 },
        { index: 8, text: '8. Me encuentro satisfecho', options: 3 },
        { index: 9, text: '9. Me siento feliz', options: 3 },
        { index: 10, text: '10. Me siento seguro', options: 3 },
        { index: 11, text: '11. Me encuentro bien', options: 3 },
        { index: 12, text: '12. Me siento molesto', options: 3 },
        { index: 13, text: '13. Me siento agradable', options: 3 },
        { index: 14, text: '14. Me encuentro atemorizado', options: 3 },
        { index: 15, text: '15. Me encuentro confuso', options: 3 },
        { index: 16, text: '16. Me siento animoso', options: 3 },
        { index: 17, text: '17. Me siento angustiado', options: 3 },
        { index: 18, text: '18. Me encuentro alegre', options: 3 },
        { index: 19, text: '19. Me encuentro contrariado', options: 3 },
        { index: 20, text: '20. Me siento triste', options: 3 },
      ],
    },
    {
      title: 'Segunda Parte: Ansiedad - Rasgo',
      instructions: 'Lee cada frase y señala la puntuación de 1 a 3 que indique mejor cómo te sientes en general, la mayoría de las veces. No hay respuestas buenas ni malas.',
      legend: ['1 = Casi nunca', '2 = A veces', '3 = A menudo'],
      questions: [
        { index: 21, text: '1. Me preocupa cometer errores', options: 3 },
        { index: 22, text: '2. Siento ganas de llorar', options: 3 },
        { index: 23, text: '3. Me siento desgraciado', options: 3 },
        { index: 24, text: '4. Me cuesta tomar una decisión', options: 3 },
        { index: 25, text: '5. Me cuesta enfrentarme a mis problemas', options: 3 },
        { index: 26, text: '6. Me preocupo demasiado', options: 3 },
        { index: 27, text: '7. Me encuentro molesto', options: 3 },
        { index: 28, text: '8. Pensamientos sin importancia me vienen a la cabeza y me molestan', options: 3 },
        { index: 29, text: '9. Me preocupan las cosas del colegio', options: 3 },
        { index: 30, text: '10. Me cuesta decidirme en lo que tengo que hacer', options: 3 },
        { index: 31, text: '11. Noto que mi corazón late más rápido', options: 3 },
        { index: 32, text: '12. Aunque no lo digo, tengo miedo', options: 3 },
        { index: 33, text: '13. Me preocupo por cosas que puedan ocurrir', options: 3 },
        { index: 34, text: '14. Me cuesta quedarme dormido por las noches', options: 3 },
        { index: 35, text: '15. Tengo sensaciones extrañas en el estómago', options: 3 },
        { index: 36, text: '16. Me preocupa lo que los otros piensen de mí', options: 3 },
        { index: 37, text: '17. Me influyen tanto los problemas, que no puedo olvidarlos durante un tiempo', options: 3 },
        { index: 38, text: '18. Tomo las cosas demasiado en serio', options: 3 },
        { index: 39, text: '19. Encuentro muchas dificultades en mi vida', options: 3 },
        { index: 40, text: '20. Me siento menos feliz que los demás chicos', options: 3 },
      ],
    },
  ],
};