import { TestConfig } from '../../models/test.interfaces';

const CUIDA_QUESTIONS = [
  "Me gusta conocer gente nueva.",
  "Tengo problemas para dormir.",
  "Estoy satisfecho de cómo soy.",
  "Si alguien me insulta intento averiguar por qué lo hace.",
  "A veces juzgo a los demás sin conocerles.",
  "Me disgusta mi aspecto físico.",
  "Tengo cambios de humor con bastante facilidad.",
  "Me gusta reunirme con amigos y conversar.",
  "Siempre hago lo que digo.",
  "Me gusta participar en experiencias nuevas.",
  "Soy una persona tranquila.",
  "Intento no herir los sentimientos de los demás.",
  "No me molesta cambiar a última hora los planes previstos para las vacaciones.",
  "Comprometerme con la gente necesitada me sirve para encontrar un sentido a la vida.",
  "Cuando coordino alguna tarea recurro a los demás si no siguen mis instrucciones.",
  "Me gustan los cambios que rompen la monotonía.",
  "Sé leer y escribir.",
  "No soporto que me lleven la contraria.",
  "Me apena pensar en las relaciones amorosas que tuve en el pasado.",
  "Cuando alguien me necesita dejo de hacer lo que estoy haciendo en ese momento para ayudarle.",
  "No hago las cosas solo para satisfacer a los demás.",
  "La gente que me rodea raramente me hace partícipe de sus problemas.",
  "Cuando dejo una relación importante, tardo muchos años en olvidarla.",
  "Intento ponerme en el lugar de los demás para comprenderles mejor.",
  "Tiendo a abarcar tantas cosas que acabo agotado.",
  "No me gusta hacerme cargo de los problemas y de la economía familiar.",
  "Hago todo lo posible por salirme con la mía.",
  "Me cuesta mucho participar en reuniones de grupo.",
  "Ya no me resulta doloroso pensar en las cosas a las que he tenido que renunciar con los años.",
  "Cuando voy de viaje evito relacionarme con otros viajeros.",
  "Me cuesta aceptar que mi relación de pareja no sea como al principio.",
  "Desconfío de las personas demasiado generosas.",
  "Mi actitud ante la vida me ha impedido resolver los problemas adecuadamente.",
  "Me relaciono fácilmente con otras personas aunque no tengamos intereses comunes.",
  "Cuando emprendo alguna acción antes he valorado los pros y los contras.",
  "Nunca me he quedado con dinero de más al recibir la vuelta de una compra.",
  "Me altero fácilmente cuando algo inesperado perturba mi vida cotidiana.",
  "Los sentimientos de los demás no me preocupan.",
  "Abandono fácilmente las tareas cuando me encuentro con ciertas dificultades.",
  "Me pongo nervioso cuando alguien me halaga.",
  "Habitualmente compro cosas que no necesito solo porque me apetecen.",
  "Me siento angustiado cuando en mi vida ocurre algo que no tengo previsto.",
  "Si presto algo y me lo devuelven estropeado, soy incapaz de decirlo.",
  "Tan pronto me siento lleno de vitalidad como profundamente cansado.",
  "Sigue siendo difícil para mí vivir con la ausencia de un ser querido.",
  "Tengo facilidad para ponerme en el lugar de los demás.",
  "Cuando alguien me critica injustamente me defiendo dialogando.",
  "Creo que las despedidas me resultan más difíciles que al resto de las personas.",
  "Me cuesta darme cuenta de si una persona se siente bien o no.",
  "En situaciones de emergencia soy capaz de pensar con tranquilidad.",
  "Nunca he visto a nadie que tuviese los ojos marrones.",
  "Evito realizar una acción cuando no tengo muy claras sus consecuencias.",
  "Me resulta bastante fácil intimar con las personas.",
  "Cuando no consigo mi objetivo la situación me resulta insoportable.",
  "Raramente pienso que me gustaría volver a la infancia.",
  "Creo que nunca superaré del todo la pérdida de esa persona que fue tan importante para mí.",
  "Suelo llevar a cabo las decisiones que previamente he tomado.",
  "A veces me entusiasmo tanto con alguna idea nueva que no pienso en los inconvenientes que pueda tener.",
  "Me siento incómodo cuando alguien se acerca demasiado.",
  "Tengo tendencia a enojarme cuando las cosas no me salen bien.",
  "Las dificultades de otros países no nos incumben, es algo que deben solucionar solo ellos.",
  "Soy una persona a la que los demás utilizan.",
  "Me es fácil conectar con la gente.",
  "No me preocupa ser rechazado por los demás.",
  "Cuando doy una fiesta consigo que mis invitados se relacionen bien entre sí.",
  "Respeto los sentimientos y emociones de los demás aunque sean diferentes a los míos.",
  "Me comporto según lo que pienso en lugar de actuar como esperan los demás.",
  "Pienso que no hay nada en mí que merezca la pena.",
  "Suelo disfrutar con la mayoría de los actos sociales a los que me invitan.",
  "Necesito ayudar a los demás.",
  "En un grupo en el que no conozco a nadie me cuesta trabajo iniciar la conversación.",
  "No suelo ponerme nervioso cuando tengo que esperar para hablar.",
  "Cuando surge algún imprevisto no me importa dejar lo que esté haciendo en ese momento.",
  "Me cuesta trabajo probar comidas nuevas.",
  "Cuando censuran en presencia de otros me siento muy desanimado y lastimado.",
  "Me cuesta encontrar nuevas soluciones a los problemas habituales.",
  "En ocasiones se me saltan las lágrimas cuando recuerdo acontecimientos tristes de mi pasado.",
  "Me comprometo a hacer tareas que luego me arrepiento de haberlas aceptado.",
  "Cuando se me acumulan los problemas me bloqueo y no sé qué hacer.",
  "Identifico fácilmente tanto las emociones negativas como positivas de los demás.",
  "En una boda, me siento incómodo cuando comparto la mesa con personas desconocidas.",
  "Para formarme una opinión tengo en cuenta los diferentes puntos de vista que me ofrecen.",
  "Me preocupa que los demás no me quieran.",
  "Cuando surge un problema prefiero que lo resuelva otro.",
  "Me cuesta mucho pedir favores.",
  "Cuando estoy ocupado en algo acepto con tranquilidad cualquier interrupción.",
  "A veces pienso que no valgo para nada.",
  "En general, me gusta la gente.",
  "Nunca bebo líquidos.",
  "Me encanta organizar fiestas con mis amigos.",
  "En alguna ocasión me he quedado con algo que no era de mi propiedad.",
  "No me cuesta trabajo asumir los cambios de mi cuerpo.",
  "Cuando estoy solo me siento triste.",
  "Antes de tomar una decisión suelo tener en cuenta todas las posibilidades.",
  "Si mi hijo adolescente me propusiera algo excepcional, en principio estaría dispuesto a escucharle.",
  "Considero que tengo menos cualidades que el resto de las personas.",
  "Necesito sentirme arropado por alguien.",
  "Es muy raro que algo o alguien me haga perder los estribos.",
  "Me siento incómodo con la gente que es diferente a mí.",
  "Alguna vez he llegado tarde a trabajar por haberme quedado dormido.",
  "No suelo responder ante las provocaciones.",
  "Si alguien me pide ayuda por cualquier motivo intento poner una excusa.",
  "Las cosas sin importancia me alteran más de lo que deberían.",
  "Cuando creo tener razón impongo mi criterio.",
  "Me resulta frustrante que las cosas no salgan como espero.",
  "Los demás me consideran una persona en quien pueden confiar sus intimidades.",
  "Me atraen mucho las situaciones que resultan nuevas e inesperadas.",
  "Cuando hago favores a los demás deben agradecérmelo.",
  "Con frecuencia pienso que no he hecho las cosas debidamente.",
  "Desde siempre me han atraído las culturas que son diferentes a la mía.",
  "Me resulta difícil respetar el turno de palabra cuando alguien está hablando.",
  "No he visto ningún coche.",
  "Nunca sería suficiente todo lo que podamos hacer por las más desfavorecidas.",
  "Suelo valorarme positivamente.",
  "Me conmueve mucho observar el sufrimiento de los más débiles.",
  "Conecto fácilmente con los sentimientos de las personas.",
  "Me cuesta mucho desprenderme de los objetos de mi infancia.",
  "No me importa lo que piensen los demás sobre mis opiniones.",
  "El que haya organizaciones que prestan ayuda a otros países me parece un gasto innecesario.",
  "Suelo reaccionar sin pensar mucho en lo que hago.",
  "Los límites y las normas nunca deben ser cuestionados o negociados con los hijos.",
  "Ante situaciones problemáticas o peligrosas me altero menos que los demás.",
  "No me suelo alterar por pequeñeces.",
  "Sufro cuando deseo tener o comprar algo que no puedo.",
  "Solo me interesan aquellas cosas que están relacionadas con mi campo de interés.",
  "Si en un restaurante recibo mal servicio hago la reclamación oportuna.",
  "Suelo reconocer las cualidades positivas que tengo.",
  "Pienso que los demás van a estar a mi lado cuando los necesite.",
  "No entiendo cómo algunas personas pueden llorar delante de otras.",
  "Alguna vez me han dado ganas de pegar a alguien.",
  "Cuando visito me gusta ir a lugares que no conozco.",
  "Si pierdo algo que me gusta mucho, enseguida consigo olvidarme de ello.",
  "Me cuesta detectar cuál es el estado de ánimo de los demás.",
  "Pienso que, en general, soy un fracasado.",
  "Todo el mundo debería colaborar con asociaciones humanitarias o benéficas.",
  "No me cuesta comprometerme emocionalmente con otras personas.",
  "Acepto con naturalidad que alguien diga cosas positivas de mí.",
  "Me cuesta comprender otras religiones.",
  "Si alguien me atrae encuentro la forma de establecer comunicación con él.",
  "Hago las cosas sin pararme a pensar.",
  "Como espero demasiado de los demás, enseguida me desilusiono.",
  "Me molesta que las personas se tomen mucho tiempo para explicar las cosas.",
  "Cuando creo en algo lo defiendo con argumentos, sin enfrentarme.",
  "Cuando me siento mal busco inmediatamente la ayuda de alguien.",
  "Me altero con facilidad cuando alguna situación rompe mi rutina.",
  "No me cuesta sobreponerme ante la pérdida de algo que quiero.",
  "Me siento ansioso cuando debo comprometerme emocionalmente con otras personas.",
  "Cuando alguien hace algo que me agrada se lo digo abiertamente.",
  "Nunca he deteriorado o roto nada que no fuese mío.",
  "Antes de tomar cualquier decisión necesito comunicarlo a mi familia y amigos para que me den su aprobación.",
  "Mis hábitos son siempre buenos y deseables.",
  "Las normas que se establecen con los hijos se deben mantener en cualquier circunstancia.",
  "Me molesta que las personas que me rodean no hagan bien sus tareas.",
  "Aunque no consiga lo que quiero, me quedo tranquilo.",
  "Mis éxitos son la justa recompensa de mi esfuerzo y mi trabajo.",
  "Nunca me ha interesado la forma de vida y la cultura de otros pueblos.",
  "Cuando consigo información privilegiada la comparto con todo aquel que la necesite.",
  "No tengo cambios de humor sin un motivo que lo justifique.",
  "Estoy de acuerdo con la expresión: \"Más vale malo conocido que lo bueno por conocer\".",
  "No me suele preocupar por cosas sin importancia.",
  "Tengo mucha dificultad para estar quieto.",
  "Siempre hay personas en quien se puede confiar completamente.",
  "La ausencia de alguien querido no me impide disfrutar plenamente de las cosas.",
  "Solo debería interesarme por los problemas propios, y no tanto los ajenos.",
  "Soy capaz de organizar el tiempo cuando tengo que realizar más de una tarea.",
  "Últimamente lloro con bastante facilidad.",
  "Nunca hablo mal de nadie.",
  "Cuando no alcanzo un objetivo que me he propuesto me cuesta mucho aceptarlo.",
  "Me siento bien dejándome llevar por los demás.",
  "Puedo hacer las cosas sin necesitar la aprobación de los demás.",
  "Me gusta aceptar que mis padres se hagan viejos.",
  "Ante una situación límite mantengo la calma.",
  "Me resulta difícil establecer nuevas relaciones.",
  "Me esfuerzo cuando alguien dice algo negativo de mí.",
  "Cuando tengo problemas intento evitarlos.",
  "Tengo muchas razones para sentirme contento conmigo mismo.",
  "Me cuesta mucho decir que no.",
  "En situaciones difíciles considero las diferentes alternativas que hay para afrontarlas.",
  "En alguna ocasión he revelado algo que me habían confiado en secreto.",
  "A veces miento.",
  "Me cuesta mucho percibir las cualidades positivas que tengo.",
  "Suelo hablar sin pensar demasiado lo que digo.",
  "Me siento mal cuando no tengo relaciones afectivas duraderas con otras personas.",
  "Se tambalean mis sentimientos y me dejo llevar cuando me desbordan.",
  "No me importa lo que los demás piensen de mí.",
  "Me considero capaz de hacer las cosas tan bien como los demás.",
  "En situaciones muy tensas me irrito.",
  "Me cuesta trabajo relacionarme con la gente cuando estoy en algún acto social.",
  "Con la cantidad de niños que necesitan un hogar me planteo tener hijos en lugar de los propios.",
];

export const CUIDA_CONFIG: TestConfig = {
  shortName: 'CUIDA',
  name: 'CUIDA - Cuestionario para la Evaluación de Adoptantes',
  description: 'Evaluación de capacidades parentales',
  totalQuestions: 189,
  optionsPerQuestion: 4,
  questionType: 'NUMERIC',
  scoringType: 'TEA',
  sections: [
    {
      title: 'CUIDA – Cuadernillo de preguntas',
      instructions: 'En este cuadernillo encontrará una serie de preguntas relacionadas con su forma de pensar y actuar en determinadas situaciones. No hay respuestas correctas ni incorrectas. Conteste con sinceridad. No deje ninguna respuesta en blanco. Las respuestas serán tratadas con confidencialidad. Marque solo una opción por pregunta según la siguiente escala.',
      legend: ['1 = En desacuerdo', '2 = Algo en desacuerdo', '3 = Algo de acuerdo', '4 = De acuerdo'],
      questions: CUIDA_QUESTIONS.map((text, i) => ({
        index: i + 1,
        text: `${i + 1}. ${text}`,
        options: 4,
      })),
    },
  ],
};