import { TestConfig } from '../../models/test.interfaces';

const PAI_QUESTIONS = [
  "Mis amigos están disponibles cuando los necesito.",
  "Tengo algunos conflictos internos que me causan problemas.",
  "Mi salud ha limitado algunas de mis actividades.",
  "En algunas ocasiones siento tanta tensión que me cuesta mucho soportarlo.",
  "A veces necesito hacer las cosas de una cierta forma para evitar ponerme nervioso.",
  "Estoy triste gran parte del tiempo sin que haya una razón para ello.",
  "Con frecuencia pienso y hablo tan deprisa que los demás no pueden seguir mi pensamiento.",
  "La mayor parte de la gente que conozco es digna de confianza.",
  "De vez en cuando pierdo completamente la memoria.",
  "Tengo algunas ideas que los demás consideran extrañas.",
  "He dañado intencionadamente algunas pertenencias de otras personas.",
  "Mi salud es muy buena para mi edad.",
  "Soy una persona muy sociable.",
  "Tengo cambios de humor repentinos.",
  "A veces me siento culpable por la cantidad de alcohol que bebo.",
  "Me encuentro a gusto en las situaciones en las que tengo que dirigir a otros.",
  "A menudo cambio la imagen y la idea que tengo sobre mí.",
  "Tengo bastante mal carácter.",
  "He tenido algunas relaciones tormentosas.",
  "En ciertas ocasiones me gustaría estar muerto.",
  "La gente tiene miedo de mi temperamento.",
  "A veces tomo drogas para sentirme mejor.",
  "He probado casi todos los tipos de drogas.",
  "A veces incluso las cosas pequeñas me preocupan demasiado.",
  "Suelo tener dificultad para concentrarme a causa de mis nervios.",
  "Con frecuencia tengo miedo de 'meter la pata' y decir algo inconveniente.",
  "Siento que he decepcionado a todo el mundo.",
  "Tengo muchas ideas brillantes.",
  "Hay personas que quieren hacerme daño.",
  "Me parece que no me relaciono bien con la gente.",
  "He pedido dinero prestado a sabiendas de que no podría devolverlo.",
  "La mayor parte del tiempo no me encuentro bien.",
  "Con frecuencia me siento inquieto.",
  "Sigo reviviendo algo horrible que me ocurrió.",
  "Casi no tengo energía.",
  "Me enfado cuando otras personas son demasiado lentas para entender mis ideas.",
  "La gente suele tratarme bastante bien.",
  "Mis pensamientos se han hecho bastante confusos.",
  "Disfruto haciendo cosas peligrosas.",
  "Mi poeta favorito es Ruperto Miralles.",
  "La mayor parte de las personas de mi entorno están cuando las necesito.",
  "Necesito hacer algunos cambios importantes en mi vida.",
  "He tenido algunas enfermedades que los médicos no han sido capaces de explicar.",
  "Mi nerviosismo me impide hacer algunas cosas bien.",
  "Tengo ciertos impulsos que lucho por controlar.",
  "He olvidado lo que es sentirse feliz.",
  "Asumo tantos compromisos que luego no soy capaz de cumplirlos.",
  "Debo estar alerta ante la posibilidad de que algunas personas no sean leales.",
  "He realizado cosas que no eran completamente legales.",
  "Mis problemas de salud son muy complicados.",
  "Me resulta fácil hacer nuevos amigos.",
  "Experimento estados de ánimo muy intensos.",
  "Tengo algunas dificultades para controlar la cantidad de alcohol que bebo.",
  "Suelo actuar como un líder de forma natural.",
  "No tengo casi ningún buen recuerdo de mi infancia.",
  "A veces otras personas meten ideas en mi cabeza.",
  "A veces tengo una intensa sensación de vacío interior.",
  "Nunca tengo problemas por culpa de mi temperamento.",
  "Quiero que algunas personas sepan que me han hecho mucho daño.",
  "He pensado en algunas formas de quitarme la vida.",
  "A veces exploto y pierdo completamente el control sobre mí.",
  "Algunas personas me han dicho que tengo problemas con las drogas.",
  "El consumo de drogas me ha producido algunos problemas de salud.",
  "No acepto bien las críticas.",
  "Con frecuencia me resulta difícil divertirme porque todo me preocupa.",
  "Tengo temores excesivamente grandes.",
  "A veces pienso que no valgo nada.",
  "Tengo muchas cualidades interesantes de las que otras personas carecen.",
  "Algunas personas hacen cosas para que quede mal.",
  "Tengo muy poco que decir a otras personas.",
  "Me aprovecharía de los demás si tuviera la oportunidad.",
  "Tengo muchos dolores.",
  "Algunas veces me preocupo tanto que me parece que voy a desmayarme.",
  "Con frecuencia me vienen recuerdos del pasado que me provocan malestar.",
  "Concilio fácilmente el sueño.",
  "No tengo paciencia con la gente que intenta frenarme.",
  "Creo que en mi vida he tenido tanta suerte como la mayor parte de la gente.",
  "Algunas veces mezclo unos pensamientos con otros.",
  "Hago muchas cosas peligrosas sólo por la emoción que me producen.",
  "A veces recibo por correo anuncios que no me interesan en absoluto.",
  "Cuando tengo problemas cuento con personas con las que puedo hablar.",
  "Tengo que cambiar en algunos aspectos, aunque me cueste mucho.",
  "En algunas ocasiones tengo miedo sin que haya motivos para ello.",
  "Alguna parte de mi cuerpo se ha quedado insensible en ocasiones, sin saber por qué.",
  "Me incomoda que las cosas no estén en su sitio.",
  "Cualquier cosa me supone un gran esfuerzo.",
  "Mis amigos no son capaces de seguir todas mis actividades sociales.",
  "La mayor parte de la gente tiene buenas intenciones.",
  "Mi destino ha sido ser infeliz desde el día en que nací.",
  "A veces parece que mis pensamientos se producen en voz alta y que los demás pueden oírlos.",
  "He dicho muchas mentiras para librarme de situaciones comprometidas.",
  "Me cuesta mucho hacer las cosas por los problemas de salud que tengo.",
  "Me gusta conocer a nuevas personas.",
  "A veces me meto en problemas porque actúo de forma muy impulsiva.",
  "Algunas personas cercanas piensan que bebo demasiado.",
  "Se me dan bien los trabajos en los que hay que dirigir a otros.",
  "Me preocupa mucho que otras personas puedan abandonarme.",
  "Cuando estoy conduciendo y me indigno con otros conductores hago que se den cuenta de ello.",
  "Algunas personas muy próximas me han abandonado.",
  "He hecho planes para matarme.",
  "Cuando me enfurezco es muy difícil calmarme.",
  "He tenido problemas económicos por el consumo de drogas.",
  "Soy incapaz de controlar mi consumo de drogas.",
  "A veces me quejo demasiado.",
  "Con frecuencia siento tal preocupación y nerviosismo que casi no puedo soportarlo.",
  "Cuando tengo que hacer algo delante de otras personas siento muchos nervios.",
  "Me siento sin fuerzas para continuar.",
  "Tengo planes que me convertirán algún día en una persona famosa.",
  "Las personas que me rodean son leales conmigo.",
  "Soy una persona solitaria.",
  "Haría cualquier cosa si me pagasen lo suficiente.",
  "Tengo buena salud.",
  "A veces siento mareos cuando he estado sometido a una presión fuerte.",
  "El recuerdo de una mala experiencia me ha afectado durante mucho tiempo.",
  "Es raro que tenga alguna dificultad para dormir.",
  "A veces me irrito porque otras personas no comprenden mis planes.",
  "He dado mucho pero es poco lo que he recibido a cambio.",
  "Algunas veces me cuesta separar unos pensamientos de otros.",
  "A veces me comporto de forma desenfrenada e insensata.",
  "El deporte que más me gusta ver por televisión es el salto de altura.",
  "Las personas que conozco se preocupan por mí.",
  "Necesito ayuda para afrontar los problemas importantes.",
  "En alguna ocasión mis piernas estaban tan débiles que no podía caminar.",
  "A menudo tengo la sensación de que está a punto de ocurrir algo horrible.",
  "Soy capaz de descansar aunque mi casa esté desordenada.",
  "Parece que nada es capaz de proporcionarme placer.",
  "En ocasiones mis pensamientos se mueven a una velocidad excesiva.",
  "La gente suele ocultar sus verdaderas intenciones.",
  "Tengo problemas psicológicos graves que comenzaron de forma repentina.",
  "Hay personas que intentan controlar mis pensamientos.",
  "Nunca he tenido conflictos con la ley.",
  "Parece que mis problemas de salud son siempre difíciles de tratar.",
  "Soy una persona acogedora.",
  "A veces no puedo contener mi rabia.",
  "Mi costumbre de beber me ha producido algunos problemas en las relaciones con los demás.",
  "Me cuesta mucho defenderme sin ayuda.",
  "A menudo me pregunto lo que debería hacer con mi vida.",
  "Sería capaz de gritar a otros con tal de que queden claros mis argumentos.",
  "Cuando estoy muy enfadado suelo hacer cosas para hacerme daño.",
  "En los últimos tiempos he estado pensando en el suicidio.",
  "A veces rompo cosas cuando estoy muy furioso.",
  "Nunca consumo drogas ilegales.",
  "Me perjudica mi comportamiento impulsivo.",
  "A veces soy demasiado impaciente.",
  "Mis amigos dicen que me preocupo demasiado.",
  "Rara vez siento miedo.",
  "Por más que lo intente, nada me sale bien.",
  "Creo que tengo las respuestas a algunas preguntas importantes.",
  "Algunas personas tratan de impedir que yo pueda progresar.",
  "Hay pocas personas a las que sienta cercanas.",
  "Pienso en mí ante todo y dejo que los demás cuiden de sí mismos.",
  "Rara vez me quejo de mi estado de salud.",
  "A veces me cuesta respirar cuando me someto a mucha tensión.",
  "Parece que no puedo librarme de ciertos acontecimientos del pasado.",
  "He estado moviéndome con más lentitud de lo normal.",
  "Tengo planes importantes y me molesta mucho que otras personas intenten meterse en medio.",
  "Muchas personas no son capaces de apreciar lo que he hecho por ellas.",
  "A veces parece que alguien está bloqueando mis pensamientos.",
  "Me gusta conducir muy deprisa.",
  "La mayor parte de la gente está deseando ir al dentista.",
  "La gente no comprende lo mucho que sufro.",
  "Tengo muchos problemas económicos.",
  "Recientemente se han producido muchos cambios en mi vida.",
  "En mi casa hay poca estabilidad.",
  "Las cosas no van bien en mi familia.",
  "He perdido el interés por cosas que antes me gustaban.",
  "Últimamente he tenido mucha más energía de la habitual.",
  "Generalmente doy por supuesto que la gente dice la verdad.",
  "Paso la mayor parte del tiempo en soledad.",
  "He oído voces que nadie más es capaz de oir.",
  "Me gusta hacer cosas sólo para comprobar si puedo salir impune de ellas.",
  "He tenido únicamente los problemas de salud que la mayoría de la gente tiene.",
  "Necesito tiempo para sentirme en confianza con personas que no conozco.",
  "Siempre he sido una persona bastante feliz.",
  "La bebida me ayuda a sobrellevar ciertas situaciones sociales.",
  "Soy el tipo de persona que se hace cargo de las cosas.",
  "No puedo soportar separarme de las personas que son muy cercanas a mí.",
  "Nunca pierdo el control por estar demasiado furioso.",
  "He cometido algunos errores graves en relación con las personas que he elegido como amigas.",
  "Durante mucho tiempo he estado pensando en el suicidio.",
  "He amenazado a otras personas con hacerlas daño.",
  "He utilizado medicamentos para animarme.",
  "Suelo tener pocos cambios de humor.",
  "A veces intento evitar a las personas que me disgustan.",
  "Mi preocupación por las cosas es similar a la de la mayoría de las personas.",
  "No me asusta conducir por autopistas.",
  "Me parece que me cuesta mucho concentrarme.",
  "He tenido algunos éxitos destacados.",
  "Algunas personas cambian sus planes para molestarme.",
  "Disfruto con la compañía de otras personas.",
  "No me gusta sentirme ligado a otra persona.",
  "Tengo problemas de espalda.",
  "Soy capaz de relajarme con facilidad.",
  "He tenido algunas experiencias terribles que hacen que me sienta culpable.",
  "Con frecuencia me despierto muy temprano por la mañana y luego no puedo volver a dormirme.",
  "Puedo ser muy exigente cuando quiero que las cosas se hagan deprisa.",
  "Generalmente se ha reconocido lo que he hecho.",
  "Mi mente tiende a saltar rápidamente de unas cosas a otras.",
  "La idea de una vida tranquila y ordenada nunca me ha interesado.",
  "Mis aficiones favoritas son el tiro con arco y la filatelia.",
  "Me gusta estar con mi familia.",
  "Me gusta cómo soy.",
  "En ciertas ocasiones he perdido la sensibilidad en las manos.",
  "Raras veces siento tensión o ansiedad.",
  "Normalmente me doy cuenta de cuando algo tiene muchos gérmenes.",
  "No me interesa la vida.",
  "Tengo la sensación de que necesito estar en constante actividad, sin descansar.",
  "La gente piensa que soy demasiado suspicaz.",
  "A veces no puedo recordar quién soy.",
  "Otras personas pueden leer mis pensamientos.",
  "Nunca me expulsaron de la escuela durante mi niñez, ni siquiera temporalmente.",
  "He tenido algunas enfermedades o molestias bastante raras.",
  "Se necesita tiempo para que otras personas lleguen a conocerme.",
  "En algunas ocasiones me he enfurecido tanto que era incapaz de manifestar toda la ira que sentía.",
  "En ocasiones he tenido que dejar la bebida.",
  "Prefiero que sean otros los que toman las decisiones.",
  "Normalmente no me aburro.",
  "Siempre que puedo evito las discusiones.",
  "Cuando tengo un amigo o amiga, lo es para mucho tiempo.",
  "La muerte sería un alivio.",
  "La gente piensa que soy una persona agresiva.",
  "Nunca consumo drogas para ayudarme a enfrentarme al mundo.",
  "Rara vez me siento una persona solitaria.",
  "A veces dejo las cosas para el último momento.",
  "Generalmente me preocupo por las cosas más de lo que debería.",
  "No me asustan las alturas.",
  "Creo que en el futuro me van a ocurrir cosas favorables.",
  "Creo que podría ser un buen cómico.",
  "Es muy raro que la gente me trate mal a propósito.",
  "Siempre que puedo me gusta estar con otras personas.",
  "No me gusta mantener una relación durante mucho tiempo.",
  "Tengo problemas de estómago.",
  "A veces noto que mi corazón late muy fuerte.",
  "Sigo teniendo pesadillas sobre el pasado.",
  "Tengo buen apetito.",
  "Me molesta mucho si alguna persona trata de impedir que cumpla mis objetivos.",
  "La gente que ha tenido éxito generalmente lo ha merecido.",
  "A veces me parece que me han robado los pensamientos.",
  "Cuando me canso de un sitio inmediatamente me voy a otro.",
  "No me gusta comprar cosas que me parecen excesivamente caras.",
  "En mi familia más que hablar discutimos.",
  "Muchos de mis problemas son consecuencia de mi actitud.",
  "He tenido experiencias de visión doble o de visión borrosa.",
  "Me sobresalto con facilidad.",
  "Los demás consideran que presto mucha atención a los detalles.",
  "En los últimos tiempos me he sentido feliz habitualmente.",
  "Últimamente tengo menos necesidad de dormir de la habitual.",
  "Generalmente las cosas no son lo que aparentan a primera vista.",
  "A veces veo sólo en blanco y negro.",
  "Tengo un sexto sentido que me avisa de las cosas que van a ocurrir.",
  "Generalmente me portaba bien cuando iba al colegio.",
  "He ido muchas veces al médico en mi vida.",
  "Intento acoger a las personas que parecen estar solas.",
  "A veces tomo una copa de una bebida alcohólica en cuanto me levanto.",
  "La bebida me ha causado algunos problemas en casa.",
  "Digo siempre lo que pienso.",
  "Suelo hacer lo que otras personas quieren que haga.",
  "A veces puedo ser una persona muy violenta.",
  "Es muy difícil hacer que me enfade.",
  "He estado pensando en lo que podría decir en una carta de suicidio.",
  "No tengo motivos para seguir viviendo.",
  "Nunca he tenido problemas en el trabajo por causa de las drogas.",
  "Gasto el dinero con demasiada facilidad.",
  "A veces hago promesas que no puedo cumplir.",
  "A veces me pongo tan nervioso que me parece que voy a morir.",
  "Evito montarme en aviones.",
  "Tengo cosas importantes que aportar.",
  "Últimamente confío tanto en mí que creo que puedo conseguir lo que me proponga.",
  "La gente me mira mal.",
  "Hago amigos con facilidad.",
  "Siempre tengo algo que decir u opinar sobre cualquier cosa.",
  "Me duele la cabeza con más frecuencia que a la mayor parte de la gente.",
  "Me sudan las manos con frecuencia.",
  "Tuve una experiencia muy mala que me ha hecho perder el interés por algunas cosas con las que antes disfrutaba.",
  "A menudo me despierto a mitad de la noche.",
  "A veces estoy muy suspicaz y me enfado con facilidad.",
  "No soy una persona que suela guardar rencor.",
  "Los pensamientos desaparecen rápidamente de mi mente.",
  "Nunca tomo riesgos si puedo evitarlo.",
  "La mayor parte de la gente prefiere ganar a perder.",
  "Paso poco tiempo con mi familia.",
  "Soy capaz de resolver mis problemas por mi cuenta.",
  "Algunas partes de mi cuerpo han quedado paralizadas en alguna ocasión.",
  "No soy de las personas que se asustan fácilmente.",
  "Me controlo de una forma muy estricta.",
  "Casi siempre soy una persona alegre y positiva.",
  "Casi nunca compro cosas por un impulso repentino.",
  "La gente tiene que ganarse mi confianza.",
  "Tengo visiones en las que me veo en la obligación de cometer ciertos delitos.",
  "No creo que existan personas capaces de leer la mente.",
  "Nunca he robado dinero u objetos de otras personas.",
  "Me gusta hablar con otras personas sobre sus problemas de salud.",
  "Soy una persona afectuosa.",
  "Nunca conduzco si he estado bebiendo.",
  "Casi nunca bebo alcohol.",
  "La gente suele pedirme opinión.",
  "Si cuando acudo a un establecimiento me atienden mal reclamo al responsable.",
  "Regaño a las personas que se lo merecen.",
  "Trato de evitar el tener que elevar la voz.",
  "Me he preguntado cómo reaccionarían otras personas si me suicidase.",
  "Tengo muchos motivos para vivir.",
  "Comparto el consumo de drogas con mis mejores amigos.",
  "Soy una persona temeraria.",
  "A veces podría haber actuado más reflexivamente de lo que lo hice.",
  "No me preocupo por la cosas que escapan a mi control.",
  "No me preocupa viajar en autobús o en tren.",
  "Tengo bastante éxito en lo que emprendo.",
  "Soy incapaz de verme como una persona famosa.",
  "Soy objeto de una conspiración.",
  "Mantengo el contacto con mis amigos y amigas.",
  "Cuando hago una promesa no siento la necesidad de cumplirla.",
  "Tengo diarreas con frecuencia.",
  "Tengo el pulso firme.",
  "Evito ciertas cosas que me traen malos recuerdos.",
  "Tengo poco interés por el sexo.",
  "Soy poco paciente con la gente que no está de acuerdo con mis planes.",
  "A la larga uno siempre se ve recompensado si ayuda a los demás.",
  "Soy capaz de concentrarme ahora tan bien como en mis mejores tiempos.",
  "No soy del tipo de personas a las que asustan los retos.",
  "En mi tiempo libre suelo leer, ver la televisión o simplemente descansar.",
  "Me gustaría entender por qué actúo en la forma en que lo hago.",
  "Mi vida es completamente impredecible.",
  "En algunas ocasiones mi vista ha empeorado y luego ha vuelto a mejorar.",
  "Soy una persona muy tranquila y relajada.",
  "La gente dice que soy perfeccionista.",
  "Me satisface plenamente mi situación laboral.",
  "Me preocupa no tener bastante dinero para salir adelante.",
  "La relación con mi pareja no va bien.",
  "Creo que dentro de mí hay tres o cuatro personalidades completamente diferentes.",
  "Soy una persona bastante comprensiva.",
  "Es importante para mí tener relaciones personales íntimas.",
  "Tengo poca paciencia con la gente.",
  "Tengo más amigos que la mayor parte de la gente que conozco.",
  "Nunca he tenido problemas por haber bebido.",
  "He tenido algunos problemas en el trabajo por culpa de la bebida.",
  "Suelo intentar que los demás no se den cuenta cuando discrepo de ellos.",
  "Soy una persona muy independiente.",
  "La gente se sorprendería si me viese gritar a alguien.",
  "Desde que soy una persona adulta nunca he empezado una pelea que haya llegado a las manos.",
  "Estoy pensando en la posibilidad de suicidarme.",
  "Las cosas nunca me han ido tan mal como para pensar en suicidarme.",
  "El consumo de drogas nunca me ha producido problemas con la familia o los amigos.",
  "Pongo mucho cuidado en la forma de gastar el dinero.",
  "Casi nunca estoy de mal humor.",
];

function buildPAISection() {
  const questions = PAI_QUESTIONS.map((text, i) => ({
    index: i + 1,
    text: `${i + 1}. ${text}`,
    options: 4,
  }));
  return [{ title: '', instructions: '', legend: [], questions }];
}

const PAI_INSTRUCTIONS = `A continuación encontrará una serie de afirmaciones. Lea cada una de ellas y decida en qué medida describe su forma de ser, sus pensamientos, sentimientos y actitudes.

Para cada frase seleccione una de las siguientes opciones:

  F  —  FALSO, no me describe en absoluto
  LV —  LIGERAMENTE VERDADERO, me describe un poco
  BV —  BASTANTE VERDADERO, me describe bastante bien
  CV —  COMPLETAMENTE VERDADERO, me describe perfectamente

Recuerde que al contestar debe dar su propia opinión. Trate de ser sincero consigo mismo y use su propio criterio. Procure contestar a todas las frases sin dejar ninguna en blanco. No hay respuestas correctas ni incorrectas.`;

export const PAI_CONFIG: TestConfig = {
  shortName: 'PAI',
  name: 'PAI - Inventario de Evaluación de la Personalidad',
  description: 'Evaluación de la personalidad y psicopatología en adultos',
  totalQuestions: 344,
  optionsPerQuestion: 4,
  questionType: 'NUMERIC',
  scoringType: 'TEA',
  optionLabels: ['F', 'LV', 'BV', 'CV'],
  globalInstructions: PAI_INSTRUCTIONS,
  questionsPerPage: 20,
  sections: buildPAISection(),
};
